name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
    
jobs:
  build-rootless:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13.2
          # Thiết lập môi trường Xcode phiên bản 13.2 trên macOS 12
            
      - uses: actions/checkout@main
        # Checkout mã nguồn của repository chính

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos
          # Checkout repository theos/theos và tất cả các submodules

      - name: Checkout SDKs
        uses: actions/checkout@main
        with:
          repository: xybp888/iOS-SDKs
          ref: master
          sparse-checkout: iPhoneOS15.5.sdk
          path: theos/sdks
          # Checkout SDK iPhoneOS15.5 từ repository xybp888/iOS-SDKs

      - name: Install dependencies
        run: brew install make xz ldid
        # Cài đặt các phụ thuộc cần thiết

      - name: Build package (rootless)
        run: THEOS=theos gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        # Build gói rootless

      - name: Upload a Build Artifact (rootless)
        uses: actions/upload-artifact@v3
        with:
          name: packages iphoneos-arm64 (rootless)
          path: packages/*_iphoneos-arm64.deb
          # Upload các build artifacts (gói rootless)

  build-rootful:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7'
          # Thiết lập môi trường Xcode phiên bản 11.7 trên macOS 11
            
      - uses: actions/checkout@main
        # Checkout mã nguồn của repository chính

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos
          # Checkout repository theos/theos và tất cả các submodules

      - name: Checkout SDKs
        uses: actions/checkout@main
        with:
          repository: xybp888/iOS-SDKs
          ref: master
          sparse-checkout: iPhoneOS14.2.sdk
          path: theos/sdks
          # Checkout SDK iPhoneOS14.2 từ repository xybp888/iOS-SDKs

      - name: Install dependencies
        run: brew install make xz ldid
        # Cài đặt các phụ thuộc cần thiết

      - name: Build package (rootful)
        run: THEOS=theos gmake clean package FINALPACKAGE=1
        # Build gói rootful

      - name: Upload a Build Artifact (rootful)
        uses: actions/upload-artifact@v3
        with:
          name: packages iphoneos-arm (rootful)
          path: packages/*_iphoneos-arm.deb
          # Upload các build artifacts (gói rootful)
